### ISSUE TITLE
Request: Support for line numbers

### ISSUE THREAD

**Issue by w3suli** [scrivo/highlight.php#28]
This project is great but there is missing one option.

Code lines can not be numbered.

There is a javascript plugin for this:
[https://github.com/wcoder/highlightjs-line-numbers.js/](https://github.com/wcoder/highlightjs-line-numbers.js/)

In the present case, it would also be an option to return an array with rows.
This could later be shaped by everyone's own needs to have tables, listings, or div elements for numbering.

**Comment by allejo** [comment]
Lack of line numbering support is intended, see https://github.com/scrivo/highlight.php/issues/19.

Same way the linked repository is a separate project, this would have to be a separate project from highlight.php as well.

If you'd like to avoid the CSS solutions, you could split up the highlighted code on each new line and wrap each line with whatever elements you'd like. The concept would be like this (untested code):

```php
$highlightedCode = '...';
$lines = explode('\R', $highlightedCode);

$output = '<div>' . implode('</div>\n<div>', $lines) . '</div>';
```

**Comment by allejo** [comment]
Since this is not the first time this feature has been asked for, I've added a demo showing why adding this to the core is not necessary: [demo/line-numbers.php](https://github.com/scrivo/highlight.php/blob/master/demo/line-numbers.php)

Styling with line numbers can be so opinionated so it's left up to the user to style it however they'd like. **highlight.php**'s goal remains the same: highlighting code 😄
