### ISSUE TITLE
demo/line-numbers.php - style changed

### ISSUE THREAD

**Issue by truefriend-cz** [scrivo/highlight.php#32]
If i use demo/line-numbers.php and set css is Dark background style then no show background Dark and text formatting missed (bad overflow, spacing, etc.) (text highlighting is ok only) .

**Comment by allejo** [comment]
Would you mind posting a snippet of the code you’re trying out?

Sounds like a CSS question, so I *think* your text is just blending into the dark background because the font color is black. If you set the font color to white or another light color, that should prevent it from blending into the dark background.

Possibly something like this?

```css
pre {
  color: white;
}
```

**Comment by allejo** [comment]
I'm going to close this issue since it's not directly related to this library's functionality. Feel free to keep asking questions related to this and I'll do my best to help out as I can.
