### ISSUE TITLE
Any Plan to Convert {language}.json to {language}.php?

### ISSUE THREAD

**Issue by taufik-nurrohman** [scrivo/highlight.php#65]
Any plan to convert `{language}.json` files to `{language}.php` files? So that we could predefine reusable data, and maybe to provide some comments in the file, so that we can return PHP array instead of JSON string that requires extra decoding process.

Example language file contents:

~~~ .php
<?php

$keywords = get_foo_keywords();
$number = \Highlighter\Highlight::NUMBER;

return [
    'case_insensitive' => true,
    'keywords' => $keywords,
    // ...
];
~~~

I can help.

**Comment by allejo** [comment]
I do not have any plans to convert the JSON files into PHP files. The performance gain for doing this would probably be fractional at best. Language definitions are saved in a static array in the `Highlighter` class meaning they're shared across all `Highlighter` instances and once they're loaded and compiled, they don't need to be reparsed again unless you explicitly tell `Highlighter` to reparse/replace the languages.

Additionally, you rarely *ever* want to compile all 185 languages at run time; even with auto-detection, you probably won't be compiling too many languages because that's just slow and causes inaccuracies.

As for highlight.js v10, they'll be changing their API and it'll probably take a few weeks or months before highlight.php can catch up since we only work with finalized/released APIs. Once v10 is released, then it might be necessary to have PHP files? Maybe we can get creative with more JSON files? But who knows? 🤷‍♂ That's a problem for once v10 is released.

**Comment by taufik-nurrohman** [comment]
Okay. If someday you need any help you can mention me :+1:

**Comment by allejo** [comment]
Will do! Thank you for the offer 😄
