### ISSUE TITLE
Update HighlightPHP to bring it even to HighlightJS

### ISSUE THREAD

**Issue by Sommerregen** [scrivo/highlight.php#8]
Dear @scrivo ,

I really appreciate your work and all your effort you put in into this project. Is there any chance to get `highlight.php` even with `highlight.js` (currently that's **release 8.9.1**)? And is this project still maintained? 

The reason: I would like to use highlight.php to render code server-side and maybe let the user decide, whether he or she uses server-side generation or wants to use the original JS verison.

**Comment by scrivo** [comment]
Hi sommerregen, 
The idea is to keep up with the major releases of highlight.js. So ideally we would have been at 8.9. Unfortunately I'm not always able to find the time. And yes, the project is still maintained by me.
Regards Geert

**Comment by Sommerregen** [comment]
Thanks, glad to hear. I was just wondering. Unfortunately I'm feeling a little bit helpless in this project, since you are crawling settings from `highlight.js` via node and I don't have such a machine running. Otherwise I could propose a PR...

**Comment by scrivo** [comment]
Hi Benny

Node is not the important thing here, previous versions did this part in a browser. Node was a logical choice because you need to build the highlight.js library anyway. It just delivers the language definitions in a more neutral language format than the original hand made js language definitions. The process to generate them is largely automatic.

Currently the main branch is equal to 8.9.1 so you can use that one if you need a version that is equal to the 8.9.1 version of highlight.js. However I will not draft a release yet because one test fails, but I will close this issue.

Best regards
Geert

**Comment by Sommerregen** [comment]
Cool thanks for all your efforts! :+1:
